@startuml
!include ./WeatherForecast.puml
!include ./Program.puml
!include ./Migrations/20230508153910_FirstMigration.puml
!include ./Migrations/20231025194820_AddFeatureFlagDbTry2.puml
!include ./Migrations/20230905211025_Analytics.puml
!include ./Migrations/ContextModelSnapshot.puml
!include ./Migrations/20230905211025_Analytics.Designer.puml
!include ./Migrations/20231025192418_AddFeatureFlagDb.Designer.puml
!include ./Migrations/20230627231510_InitialCreate.puml
!include ./Migrations/20230508153910_FirstMigration.Designer.puml
!include ./Migrations/20231025192418_AddFeatureFlagDb.puml
!include ./Migrations/20230627231510_InitialCreate.Designer.puml
!include ./Migrations/20231025194820_AddFeatureFlagDbTry2.Designer.puml
!include ./Infra/Repo/FeatureFlagRepo.puml
!include ./Infra/Repo/ScopeRepo.puml
!include ./Infra/Repo/UserRepo.puml
!include ./Infra/Repo/AbListRepo.puml
!include ./Infra/Repo/Context.puml
!include ./Core/RepoContract/IAnalyticsRepo.puml
!include ./Core/RepoContract/IFeatureFlagRepo.puml
!include ./Core/RepoContract/IScopeRepo.puml
!include ./Core/RepoContract/IAbListRepo.puml
!include ./Core/RepoContract/IUserRepo.puml
!include ./Core/Models/User.puml
!include ./Core/Models/Analytics.puml
!include ./Core/Models/Scope.puml
!include ./Core/Models/FeatureFlag.puml
!include ./Core/Models/AbList.puml
!include ./Core/Services/AbService.puml
!include ./Core/Services/UserService.puml
!include ./Core/Services/FeatureFlagService.puml
!include ./Core/Services/AnalyticsService.puml
!include ./Core/Services/ScopeService.puml
!include ./obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./obj/Debug/net7.0/fnbs.MvcApplicationPartsAssemblyInfo.puml
!include ./obj/Debug/net7.0/fnbs.GlobalUsings.g.puml
!include ./obj/Debug/net7.0/fnbs.AssemblyInfo.puml
!include ./Infra/Https/Controllers/ScopesController.puml
!include ./Infra/Https/Controllers/UserController.puml
!include ./Infra/Https/Controllers/FeatureFlagController.puml
!include ./Infra/Https/Controllers/AbListController.puml
!include ./Infra/Https/Controllers/AnalyticsController.puml
!include ./Core/Models/Dtos/CheckAbTestDTO.puml
!include ./Core/Models/Dtos/ResponseWrapper.puml
!include ./Core/Models/Dtos/CreateAnalyticsDTO.puml
!include ./Core/Models/Dtos/CreateAFeatureFlag.puml
!include ./Core/Models/ServicesContract/IAbListService.puml
!include ./Core/Models/ServicesContract/IFeatureFlagService.puml
!include ./Core/Models/ServicesContract/IUserService.puml
!include ./Core/Models/ServicesContract/IAnalyticsService.puml
!include ./Core/Models/ServicesContract/IScopesService.puml
!include ./Core/Models/Dtos/Out/AbListResponse.puml
!include ./Core/Models/Dtos/Out/ScopeAdminDTO.puml
!include ./Core/Models/Dtos/Out/FeatureFlagResponse.puml
@enduml
